# Generated by Django 5.2.4 on 2025-08-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
