# Generated by Django 5.2.4 on 2025-08-09 09:46

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_is_promoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='hotel',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='destination_city', chained_model_field='city', on_delete=django.db.models.deletion.CASCADE, to='trips.hotel'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.trip')),
            ],
        ),
    ]
