# Generated by Django 5.2.4 on 2025-08-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_hotel_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='buyer_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
